{
    "name" : "Maintenance Parts Inventory",
    "version" : "b.1",
    "author" : "I Dream of ERP - Justin Mangini",
    'category': 'Human Resources',
    "depends" : ['maintenance', 'stock', 'maintenance_plan', 'base_maintenance'],
    "init_xml" : [],
    "demo_xml" : [],
    "description": "Adds parts inventory managment to Equipments module",
    'data': ['views/views.xml', 'data/data.xml'],
    'test': [],
    'installable': True,
    'auto_install': False,
    'certificate': '',
    'images': [''],
}
