{
    "name" : "Maintenance Plan - Calibration",
    "version" : "1.0",
    "author" : "I Dream of ERP - Justin Mangini",
    'category': 'Human Resources',
    "depends" : ['maintenance', 'uom_additional_uom', 'maintenance_plan' ],
    "init_xml" : [],
    "demo_xml" : [],
    "description": "Adds Calibration to maintenance plans",
    'data': ['security/security.xml','data/data.xml'],
    'test': [],
    'installable': True,
    'auto_install': False,
    'certificate': '',
    'images': [''],
}
