{
    "name" : "Equipment Maintenance Scheduler",
    "version" : "10.0.1",
    "author" : "Justin Mangini",
    'category': 'Human Resources',
    "depends" : ['maintenance', 'maintenance_req_tabbed'],
    "init_xml" : [],
    "demo_xml" : [],
    "description": "Maintenance Scheduler",
    'data': ['views/views.xml','data/data.xml'],
    'test': [],
    'installable': True,
    'auto_install': False,
    'certificate': '',
    'images': [''],
}
